import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/domain/header";
import { Footer } from "@/domain/footer";

export const metadata: Metadata = {
  title: "Kalita - Developement Website",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
